# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b24e58b991008abd6deb1566819ba449c3bada27d1d7384bcc1c66346f38c60ec880f6e928f4ab4b48454fcab138baa13c49dc6a843e406d0fce164e5d96e21

test:
  secret_key_base: d228293de5e0ff2530ef242498fef6f929cea52348d3f6a314a4e6744973f7b437378654dd17f929421c059ab31b5a098cd6c7a408dbccb636b526f102ef693c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
